import React from "react"
import { DsBox } from "./DsBox.Component"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DsBox,
  "https://www.figma.com/design/C9TREbo9kCnImBjcO1zRkG/Subzero-V.2.0-playground?node-id=12666-98079&m=dev",
  {
    props: {
      children: figma.children('*'),
      width: figma.string('properties')
    },
    example: (props) => <DsBox>{props.children}</DsBox>,
  },
)
