export type DsRulesKeys =
  | 'headerMobileHeight'
  | 'headerDesktopHeight'
  | 'appBarMobileMinHeight'
  | 'stepperConnectorMinHeight'
  | 'searchbarMinWidth'
  | 'searchbarHeight'
  | 'drawerWidth'
  | 'drawerMiniWidth'
  | 'dialogMdMaxWidth'
  | 'bottomSheetWorkingAreaHeight'
  | 'avatarSSize'
  | 'avatarMSize'
  | 'avatarLSize'
  | 'avatarXLSize'
  | 'avatarXXLSize'
  | 'avatar3XLSize'
  | 'formHelperTextMinHeight'
  | 'buttonLargeLoaderWidth'
  | 'buttonMediumLoaderWidth'
  | 'buttonSmallLoaderWidth'
  | 'dataGridRowMinHeight'
  | 'dataGridColumnHeaderHeight'

export type DsRules = { [key in DsRulesKeys]: string }
